
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myaccounts
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      WAIT_HOSTS: postgres:5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    
      

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4100:80"
    depends_on:
      - backend

volumes:
  pgdata: 